1️⃣ Introduction
Dataset choisi

Breast Cancer Wisconsin Diagnostic

Description

Dataset contenant des mesures numériques issues d’images de biopsies mammaires.

In [2]:
#Atelier pratique Groupe 1se

#PARTIE 1 EDA
# 📚 Importation des bibliothèques/modules
import pandas as pd   # bibliothèque utilisée pour manipuler des tableaux de données
import os             # bibliothèque permettant de manipuler les chemins de fichiers
import seaborn as sns # seaborn est une bibliothèque Python utilisée pour créer des graphiques statistiques plus lisibles que matplotlib
import matplotlib.pyplot as plt   # matplotlib permet d'afficher les graphiques
import numpy as np                  # numpy permet de faire des calculs statistiques 

from ucimlrepo import fetch_ucirepo

In [3]:
# 📥 Chargement du dataset Breast Cancer Wisconsin (Diagnostic)

breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17)

In [4]:
# 📊 Récupérer les variables explicatives
X = breast_cancer_wisconsin_diagnostic.data.features

# 🎯 Récupérer la variable cible
y = breast_cancer_wisconsin_diagnostic.data.targets

# 🔗 Fusionner les deux
df = pd.concat([X, y], axis=1)

# ⚠️ Le package ucimlrepo renomme les colonnes en utilisant les suffixes 1, se et  worst
# à la place des noms originaux du dataset UCI : mean, se (standard error) et worst.
# Nous restaurons ici les noms scientifiques des variables.

df.columns = (
    df.columns
    .str.replace(r'1$', '_mean', regex=True)
    .str.replace(r'se$', '_se', regex=True)
    .str.replace(r' worst$', '_worst', regex=True)
)

Chaque ligne correspond à une observation de cellule tumorale.

Les variables représentent des caractéristiques mesurées sur les cellules :

rayon

texture

périmètre

aire

compacité

concavité

etc.

Objectif du dataset

Prédire si une tumeur est Maligne (Malignant) / Bénigne (Benign)

se️⃣ Data Canvas – Compréhension du dataset
se.1 Variable principale

Variable cible :

Diagnosis

M → Malignant

B → Benign

C’est la variable que l’on voudra prédire dans un futur modèle de machine learning.

se.se Hypothèses possibles

Hypothèses exploratoires :

Les tumeurs malignes pourraient avoir un rayon plus grand

Les tumeurs malignes pourraient être plus irrégulières

Certaines variables pourraient être fortement corrélées

Ces hypothèses seront explorées dans l’EDA.

 worst️⃣ Analyse de forme

➡️ Structure du dataset

Objectif : comprendre comment les données sont organisées

Points à analyser :

In [5]:
df.shape #(nombre de lignes, nombre de colonnes)

(569, 31)

In [6]:
df.columns

Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Diagnosis'],
      dtype='str')

Les variables du dataset correspondent à des caractéristiques morphologiques
mesurées sur les noyaux de cellules issues d’images de biopsies mammaires.
Ces mesures décrivent la taille, la forme et la complexité du contour des cellules.

Traduction pédagogique des variables

| Colonne               | Traduction                 | Définition simple                                               |
| ----------------------| -------------------------- | --------------------------------------------------------------- |
| Diagnosis             | Diagnostic                 | Indique si la tumeur est bénigne (B) ou maligne (M).            |
| radius mean           | Rayon moyen                | Taille moyenne du noyau de la cellule observée.                 |
| texture mean          | Texture moyenne            | Variation d’intensité dans l’image (aspect granuleux du tissu). |
| perimeter mean        | Périmètre moyen            | Longueur du contour du noyau cellulaire.                        |
| area mean             | Aire moyenne               | Surface du noyau cellulaire.                                    |
| smoothness mean       | Lissage moyen              | Régularité du contour du noyau.                                 |
| compactness mean      | Compacité moyenne          | Mesure de la compacité : relation entre périmètre et surface.   |
| concavity mean        | Concavité moyenne          | Profondeur moyenne des creux dans le contour du noyau.          |
| concave_points mean   | Points concaves moyens     | Nombre de zones creusées dans le contour.                       |
| symmetry mean         | Symétrie moyenne           | Degré de symétrie de la cellule.                                |
| fractal_dimension mean| Dimension fractale moyenne | Complexité géométrique du contour du noyau.                     |

Variables de variabilité (erreur standard)

| Colonne              | Traduction                        | Définition                                    |
| ---------------------| --------------------------------- | --------------------------------------------- |
| radius se            | Variabilité du rayon              | Variation du rayon entre différentes mesures. |
| texture se           | Variabilité de texture            | Variation de la texture observée.             |
| perimeter se         | Variabilité du périmètre          | Variation du contour du noyau.                |
| area se              | Variabilité de surface            | Variation de la taille du noyau.              |
| smoothness se        | Variabilité du lissage            | Variation de la régularité du contour.        |
| compactness se       | Variabilité de compacité          | Variation de la compacité du noyau.           |
| concavity se         | Variabilité de concavité          | Variation des creux du contour.               |
| concave_points se    | Variabilité des points concaves   | Variation du nombre de creux.                 |
| symmetry se          | Variabilité de symétrie           | Variation de la symétrie de la cellule.       |
| fractal_dimension se | Variabilité de dimension fractale | Variation de la complexité du contour.        |

Variables "pire cas" (valeur maximale)
| Colonne                 | Traduction                  | Définition                          |
| ----------------------- | ----------------------------|-------------------------------------|
| radius worst            | Rayon maximal               | Plus grand rayon mesuré.            |
| texture worst           | Texture maximale            | Texture la plus marquée observée.   |
| perimeter worst         | Périmètre maximal           | Plus grand contour observé.         |
| area worst              | Surface maximale            | Plus grande surface du noyau.       |
| smoothness worst        | Lissage maximal             | Régularité maximale observée.       |
| compactness worst       | Compacité maximale          | Compacité la plus élevée observée.  |
| concavity worst         | Concavité maximale          | Creux les plus profonds du contour. |
| concave_points worst    | Points concaves maximum     | Nombre maximum de creux observés.   |
| symmetry worst          | Symétrie maximale           | Symétrie la plus élevée observée.   |
| fractal_dimension worst | Dimension fractale maximale | Complexité maximale du contour.     |

In [7]:
df.head(5)

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,M

In [8]:
df.info() #types des variables

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   radius_mean              569 non-null    float64
 1   texture_mean             569 non-null    float64
 2   perimeter_mean           569 non-null    float64
 3   area_mean                569 non-null    float64
 4   smoothness_mean          569 non-null    float64
 5   compactness_mean         569 non-null    float64
 6   concavity_mean           569 non-null    float64
 7   concave_points_mean      569 non-null    float64
 8   symmetry_mean            569 non-null    float64
 9   fractal_dimension_mean   569 non-null    float64
 10  radius_se                569 non-null    float64
 11  texture_se               569 non-null    float64
 12  perimeter_se             569 non-null    float64
 13  area_se                  569 non-null    float64
 14  smoothness_se            569 non-null    float64
 15  compactness_se           569 non-null    float64
 16  concavity_se             569 non-null    float64
 17  concave_points_se        569 non-null    float64
 18  symmetry_se              569 non-null    float64
 19  fractal_dimension_se     569 non-null    float64
 20  radius_worst             569 non-null    float64
 21  texture_worst            569 non-null    float64
 22  perimeter_worst          569 non-null    float64
 23  area_worst               569 non-null    float64
 24  smoothness_worst         569 non-null    float64
 25  compactness_worst        569 non-null    float64
 26  concavity_worst          569 non-null    float64
 27  concave_points_worst     569 non-null    float64
 28  symmetry_worst           569 non-null    float64
 29  fractal_dimension_worst  569 non-null    float64
 30  Diagnosis                569 non-null    str
dtypes: float64(30), str(1)
memory usage: 137.9 KB

In [9]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [10]:
df.isna().sum() # présence de valeurs manquantes

radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave_points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave_points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave_points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
Diagnosis                  0
dtype: int64

Aperçu des données

Questions à répondre :

Combien d'observations ?

Combien de variables ?

Les variables sont-elles numériques ?

Y a-t-il des valeurs manquantes ?

4️⃣ Analyse de fond

➡️ Comprendre le contenu des données

Objectif :

Analyser ce que les variables représentent réellement

À décrire :

les variables

leur signification

leur unité éventuelle

leur rôle possible

Exemple :

Variable	Description
radius_mean	moyenne du rayon
texture_mean	variation de la texture
perimeter_mean	périmètre moyen
area_mean	surface moyenne

In [11]:
# 🔍 Nombre de doublons dans le dataframe
df.duplicated().sum()

np.int64(0)

5️⃣ Analyse univariée

Analyse d’une variable seule

Objectif :

comprendre les distributions

détecter les valeurs extrêmes

observer la répartition des classes

Graphiques recommandés :

histogrammes

boxplots

Exemples :

distribution de radius_mean

distribution de area_mean

distribution de diagnosis

6️⃣ Analyse bivariée

Analyse de la relation entre deux variables

Objectif :

voir si certaines variables différencient les classes

Exemples :

radius_mean vs diagnosis

area_mean vs diagnosis

Graphiques :

scatter plots

boxplots par classe

violin plots

7️⃣ Analyse multivariée

Analyse de plusieurs variables en même temps

Objectifs :

détecter des patterns

observer les corrélations

Graphiques recommandés :

pairplot

matrice de corrélation

heatmap

8️⃣ Analyse des biais et qualité des données

Points à discuter :

Valeurs manquantes

Y a-t-il des données manquantes ?

Valeurs aberrantes

Certaines observations sont-elles très éloignées ?

Déséquilibre de classes

Nombre de :

Bénin

Malin

9️⃣ Synthèse des observations

Répondre aux questions :

quelles variables semblent les plus importantes ?

quelles variables sont corrélées ?

quelles variables différencient le mieux malin vs bénin ?

🔟 Perspective future

Objectif potentiel :

Construire un modèle de classification pour prédire :

Malin vs Bénin

Exemples de modèles possibles :

Logistic Regression

Random Forest

SVM

⚠️ Mais aucun modèle dans cet atelier.